### ISSUE TITLE
以后是否考虑加入Chromium Edge应用商店？

### ISSUE THREAD

**Issue by Admin-Account** [gautamkrishnar/motrix-chrome-extension#15]
国内环境下获取谷歌官方插件还是很麻烦的，镜像站又怕夹带私货。希望在商家谷歌商店的同时也兼顾一下Chromium Edge，希望能在测试结束后将此计划提上日程，谢谢！

**Comment by brightzoe** [comment]
I love this extension! It's very convenient to use! Thank U very much!

Same as above, I'm looking forward to use it on Microsoft Edge extension store!

Looking forward to coming soon，THX~~😊

@gautamkrishnar

**Comment by gautamkrishnar** [comment]
Thanks, Edge support is getting added on #13 will merge it soon.
