### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by huyndnse63331** [gautamkrishnar/motrix-chrome-extension#4]
Hi, i followed every steps in the video but it didn't work for me. I'm using Chrome (81.0.4044.138) on Ubuntu 18.04.4 (amd64). After finishing setting 2 RPC keys for the Chrome extension and Motrix, my Chrome still downloaded file with the native downloader. Please kindly check this issue. Thank you.

Motrix version: 1.5.10

**Comment by jewel-snake** [comment]
Same on Arch Linux x64
`~> chromium --version
Chromium 81.0.4044.138 Arch Linux`
motrix version is 1.5.10
and it's definitely running, checked with systemctl.
As I'm not professional in javascript 4 chrome development, maybe I'm wrong, but you're requiring 'motrixapikey' in line 9,
and use it only to check if it's not set(line 14), and nowhere else. Maybe it should somehow figure in json params.

**Comment by gautamkrishnar** [comment]
@jewel-snake thanks a lot for taking your time to research this. This was the exact issue.

**Comment by gautamkrishnar** [comment]
@jewel-snake @huyndnse63331 can you please test https://github.com/gautamkrishnar/motrix-chrome-extension/releases/tag/1.0.6 and let me know if it's fixed?

**Comment by gautamkrishnar** [comment]
I Don't have access to any Linux machine to test this out myself right now. Please feel free to reopen the issue if it's not fixed. I am also not sure about the aria2c API.

**Comment by huyndnse63331** [comment]
Hi, this issue wasn't fixed completely in this release (v1.0.6). I'll attach the video which i recorded its behavior below.

After setting up RPC keys completely, click on the link i wanted to download, it'll download with the Chrome native downloader, after pressing `ctrl + j`, it'll show a popup that transfered to Motrix, but when i opened Motrix, nothing was downloading.

Concept video:
https://streamable.com/zzdeaq

**Comment by gautamkrishnar** [comment]
@huyndnse63331 thanks for testing

**Comment by jewel-snake** [comment]
Found the bug, fixed and created fork with better code. As I've never did this before, I have no experience in suggesting code improvements, so write if you can't see mine. However, new weird behaving came up : 
1. On downloads [wallhere](wallhere.com) site sends js file, which contains mirrorlist, where the file you want could be downloaded. Chrome executes the script and download only required file.
2. after changing site I must reload the extension every time e.g. I open reddit, open any post, I can download it via motrix, but when I open any other post, motrix don't work. Here is the [video](https://streamable.com/2xjs04), the first picture really downloaded as we want, but the second didn't.

**Comment by hthre7** [comment]
also in linux mint 19.3 using chromium 81.0.4044.138 with motrix 1.5.10 
same behaviour

**Comment by luxl** [comment]
Using the latest version, still not working. I'm using Manjaro 20.1 with Chrome 83.

**Comment by hthre7** [comment]
> 2. after changing site I must reload the extension every time e.g. I open reddit, open any post, I can download it via motrix, but when I open any other post, motrix don't work. Here is the [video](https://streamable.com/2xjs04), the first picture really downloaded as we want, but the second didn't.

exactly the extension need every download a reload to work and need persistent runtime.

**Comment by gautamkrishnar** [comment]
Thanks a lot everyone for testing this out. Please try out the beta version and let me know if its fixed: https://github.com/gautamkrishnar/motrix-chrome-extension/releases/tag/1.0.7-beta

Sorry for the trouble, I don't have a Linux machine to test it out myself.

**Comment by huyndnse63331** [comment]
sorry, still not working, its downloading with chrome native downloader. Why don't you use VM for testing?

**Comment by gautamkrishnar** [comment]
@huyndnse63331 Yep on it, that's the only option now 😓

**Comment by jewel-snake** [comment]
@gautamkrishnar your code is not working because you haven't fixed line 52. hash is PARAMS.params[2] !

**Comment by gautamkrishnar** [comment]
@jewel-snake thanks for the suggestion i am rewriting the code with Aria2.js so that I can use WebSocket instead of HTTP calls. Looks like its working for me on mac. Will test it out in Linux vm.

**Comment by gautamkrishnar** [comment]
I had to abandon the WebSocket due to some connection refused error handling. Due to the implementation of WebSocket code in the library I was not able to do proper error handling

**Comment by gautamkrishnar** [comment]
@huyndnse63331 @jewel-snake can you guys please try out https://github.com/gautamkrishnar/motrix-chrome-extension/releases/tag/1.0.7-beta2 when you guys get some time and let me know the feedback on it. I had added a console log to see if there are any errors. Which can be debugged by going to the console: https://developer.chrome.com/extensions/tut_debugging

**Comment by huyndnse63331** [comment]
sorry, i don't know how to debug your extension, but its still downloading with chrome :(

**Comment by zmm2tysu** [comment]
extension version: 1.0.7-beta2
motrix version: 1.5.10
still not working,maybe the problem is the extension do not have permission to access other website(I founded it in chrome://extensions)

**Comment by jewel-snake** [comment]
@gautamkrishnar still works only before refresh. Extension manager says `background page(inactive)` after each download. It seems like the script stops.

Also, console debugging doesn't effective because the code does not rise any exceptions, `console.log` does not appear in it though.

**Comment by poseidon-j** [comment]
what is the api key?

**Comment by hthre7** [comment]
> https://github.com/gautamkrishnar/motrix-chrome-extension/releases/tag/1.0.7-beta2

now is working but without a way to choose where to download

**Comment by hthre7** [comment]
@gautamkrishnar tried removing `"persistent": false` from manifest.json is helping and work as normal still testing but you could try it.
